apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: ingresscontroller
  namespace: openshift-ingress-operator
spec:
  tolerations:
  - key: "zone"
    operator: "Equal"
    value: "frontend"
    effect: "NoSchedule"
  endpointPublishingStrategy:
    type: HostNetwork 
  domain: domain
  replicas: 2
  nodePlacement:
    nodeSelector:
      matchLabels:
        node-role.kubernetes.io/frontend-worker: ""
  routeSelector:
    matchExpressions:
      - key: zone
        operator: In
        values:
        - frontend