apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

namespace: bouvier
namePrefix: selma-

commonLabels:
  app: selma

patches:

-  target:
    version: v1
    group: apps
    kind: Deployment
    name: deployment
   patch: |-
    - op: add
      path: /spec/template/metadata/labels/zone
      value: application
    - op: add
      path: /spec/template/spec/nodeSelector/'node-role.kubernetes.io/application-worker'
      value: ""

-  target:
    version: v1
    group: route.openshift.io
    kind: Route
    name: route
   patch: |-
    - op: replace
      path: /spec/to/name
      value: selma-service

configMapGenerator:
- name: container-helper-yaml
  files:
  - container-helper.yaml
