apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: route
  labels:
    app: name
    app.kubernetes.io/instance: name
spec:
  host: hostname
  port:
    targetPort: 8080
  to:
    kind: Service
    name: service
    weight: 100
  wildcardPolicy: None