apiVersion: v1
data:
  container-helper.yaml: |+
    ---
    response: "patty"
    tcpchecks:
      - name: marge.simpson
        host: marge-service.simpson
        port: 8080
      - name: homer.simpson
        host: homer-service.simpson
        port: 8080
      - name: selma.bouvier
        host: selma-service.bouvier
        port: 8080
kind: ConfigMap
metadata:
  labels:
    app: patty
  name: patty-container-helper
