apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

namespace: bouvier
namePrefix: patty-

commonLabels:
  app: patty

patches:
-  target:
    version: v1
    group: route.openshift.io
    kind: Route
    name: route
   patch: |-
    - op: replace
      path: /spec/to/name
      value: patty-service

configMapGenerator:
- name: container-helper-yaml
  files:
  - container-helper.yaml
