
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: deny-all
  namespace: simpson
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-application-to-internal
  namespace: simpson
spec:
  podSelector:
    matchLabels:
      zone: internal
  ingress:
    - from:
        - podSelector:
            matchLabels:
              zone: application
          namespaceSelector: {}