apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-internal
  namespace: simpson
  annotations:
    argocd.argoproj.io/sync-options: Validate=false
spec:
  podSelector: null
  ingress:
    - from:
      - podSelector: {}
