apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base


patches:

patches:
-  target:
    version: v1
    group: route.openshift.io
    kind: Route
    name: route
   patch: |-
    - op: replace
      path: /spec/host
      value: patty-route-bouvier.frontend.ocp.my.lab
    - op: replace
      path: /spec/to/name
      value: patty-service
    - op: replace
      path: /metadata/name
      value: patty-route-frontend
    - op: add
      path: /metadata/namespace
      value: bouvier
    - op: replace
      path: /metadata/labels/app
      value: patty
    - op: replace
      path: /metadata/labels/zone
      value: frontend