apiVersion: v1
data:
  container-helper.yaml: |+
    ---
    response: "Homer"
    tcpchecks:
      - name: marge.simpson
        host: marge-service.simpson
        port: 8080
      - name: selma.bouvier
        host: selma-service.bouvier
        port: 8080
      - name: patty.bouvier
        host: patty-service.bouvier
        port: 8080
kind: ConfigMap
metadata:
  labels:
    app: homer
  name: homer-container-helper
